apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: ado-webui
    app.kubernetes.io/part-of: automotive-dev-operator
  name: ado-webui-oauth-proxy
stringData:
  cookie-secret: ""
type: Opaque
