apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: build-api
    app.kubernetes.io/name: automotive-dev-operator
  name: ado-build-api-oauth-proxy
stringData:
  cookie-secret: ""
type: Opaque
