apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: webui
    app.kubernetes.io/name: ado-webui
    app.kubernetes.io/part-of: automotive-dev-operator
  name: ado-webui
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app.kubernetes.io/name: ado-webui
    app.kubernetes.io/part-of: automotive-dev-operator
  type: ClusterIP
status:
  loadBalancer: {}
