apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-pod-annotator
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-pod-annotator
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: system
