apiVersion: automotive.sdv.cloud.redhat.com/v1
kind: AutomotiveDevConfig
metadata:
  labels:
    app.kubernetes.io/name: automotive-dev-operator
    app.kubernetes.io/managed-by: kustomize
    environment: development
  name: config
  namespace: automotive-dev-operator-system
spec:
  buildConfig:
    #     useMemoryVolumes: true
    #     memoryVolumeSize: "8Gi"
    pvcSize: "8Gi"

