## Append samples of your project ##
resources:
- automotive_v1_imagebuild.yaml
- automotive_v1_operatorconfig.yaml
- automotive_v1alpha1_image.yaml
- automotive_v1alpha1_catalogimage.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
