apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: operator-deployment-test
  namespace: default
spec:
  application: automotive-dev-operator
  resolverRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/centos-automotive-suite/automotive-dev-operator
      - name: revision
        value: main
      - name: pathInRepo
        value: .tekton/integration-tests/operator-deployment-test-pipeline.yaml
  contexts:
    - name: application
      description: Test operator deployment and basic functionality
  environment:
    name: development
    type: POC
    configuration:
      env:
        - name: NAMESPACE
          value: automotive-dev-operator-test

