apiVersion: appstudio.redhat.com/v1alpha1
kind: Application
metadata:
  name: automotive-dev-operator
  namespace: default
spec:
  displayName: Automotive Dev Operator
  description: A controller that manages automotive OS image builds powered by automotive-image-builder
  gitOpsRepository:
    url: https://github.com/centos-automotive-suite/automotive-dev-operator

